### ISSUE TITLE
Padding / cutting columns option

### ISSUE THREAD

**Issue by adrien-cotte** [adrien-cotte/majority-judgment#29]
Google Forms CSV has this header:

```
<date>,Choice1,Choice2,...
```

We should add a option to ignore the first column.

**Comment by RomainDereu** [comment]
Hello there!
I'd like to add this option if help is needed.

**Comment by adrien-cotte** [comment]
Great, feel free to open a PR for that.

Many thx :-) !

**Comment by RomainDereu** [comment]
Done!
Feel free to ask me for any changes you deem necessary.
https://github.com/adrien-cotte/majority-judgment/pull/31
